/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef OPENGLES_3X_NATIVE_SIMPLE_RENDERER_H
#define OPENGLES_3X_NATIVE_SIMPLE_RENDERER_H

#include "native_base_renderer.h"

class NativeSimpleRenderer : public NativeBaseRenderer {

public:

    void surfaceCreated();

    void surfaceChanged(unsigned int width, unsigned int height);

    void onDrawFrame();

};

#endif
