/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_handy_opengles_color_NativeColorRenderer */

#ifndef COM_HANDY_OPENGLES_COLOR_NATIVECOLORRENDERER
#define COM_HANDY_OPENGLES_COLOR_NATIVECOLORRENDERER
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL surfaceCreated(JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL surfaceChanged(JNIEnv *, jobject, jint, jint);

JNIEXPORT void JNICALL onDrawFrame(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
