/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_opengles_color_NativeColorRenderer */

#ifndef _Included_com_onzhou_opengles_color_NativeColorRenderer
#define _Included_com_onzhou_opengles_color_NativeColorRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onzhou_opengles_color_NativeColorRenderer
 * Method:    surfaceCreated
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_onzhou_opengles_color_NativeColorRenderer_surfaceCreated
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_onzhou_opengles_color_NativeColorRenderer
 * Method:    surfaceChanged
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_onzhou_opengles_color_NativeColorRenderer_surfaceChanged
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_onzhou_opengles_color_NativeColorRenderer
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_onzhou_opengles_color_NativeColorRenderer_onDrawFrame
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
