/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_opengles_triangle_NativeTriangleRenderer */

#ifndef _Included_com_onzhou_opengles_triangle_NativeTriangleRenderer
#define _Included_com_onzhou_opengles_triangle_NativeTriangleRenderer
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_onzhou_opengles_triangle_NativeTriangleRenderer
 * Method:    surfaceCreated
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_onzhou_opengles_triangle_NativeTriangleRenderer_surfaceCreated
        (JNIEnv *, jobject);

/*
 * Class:     com_onzhou_opengles_triangle_NativeTriangleRenderer
 * Method:    surfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_onzhou_opengles_triangle_NativeTriangleRenderer_surfaceChanged
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_onzhou_opengles_triangle_NativeTriangleRenderer
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_onzhou_opengles_triangle_NativeTriangleRenderer_onDrawFrame
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
