/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_opengles_color_NativeColorRenderer */

#ifndef COM_ONZHOU_OPENGLES_COLOR_NATIVECOLORRENDERER
#define COM_ONZHOU_OPENGLES_COLOR_NATIVECOLORRENDERER
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL drawColor(JNIEnv *, jobject, jobject, jint);

JNIEXPORT void JNICALL drawBitmap(JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
