/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_opengles_triangle_NativeTriangleRenderer */

#ifndef _Included_com_onzhou_opengles_triangle_NativeTriangleRenderer
#define _Included_com_onzhou_opengles_triangle_NativeTriangleRenderer
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL surfaceCreated(JNIEnv *, jobject);

JNIEXPORT void JNICALL surfaceChanged(JNIEnv *, jobject, jint, jint);

JNIEXPORT void JNICALL onDrawFrame(JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
